site_name: SALTA Wiki
site_url: https://AdrianArtacho.github.io/salta_wiki/
repo_url: https://github.com/AdrianArtacho/salta_wiki
theme:
  name: material
  logo: media/logo.png
  language: en
nav:
  - Home: docs/index.md
  - Getting Started: docs/getting-started.md
  - User Guide:
      - Overview: docs/user-guide/overview.md
      - Data Input: docs/user-guide/data-input.md
  - Installation: docs/installation.md
  - About: docs/about.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

