site_name: SALTA Wiki
site_url: https://AdrianArtacho.github.io/salta_wiki/
repo_url: https://github.com/AdrianArtacho/salta_wiki
theme:
  name: material
  logo: media/logo.png
  language: en
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
      - Overview: user-guide/overview.md
      - Data Input: user-guide/data-input.md
  - Installation: installation.md
  - About: about.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

